# Generated by Django 4.0.5 on 2022-08-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('full_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lyrics', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_data', models.TextField(blank=True, db_column='data')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('imagescol', models.CharField(max_length=45)),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.TextField()),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.user')),
            ],
        ),
    ]
