# Generated by Django 4.0.5 on 2022-08-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
