# Generated by Django 4.1 on 2022-08-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_User',
        ),
    ]
