# Generated by Django 4.1 on 2022-09-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_loginuser'),
        ('main_page', '0007_alter_compose_adminid_alter_images_memberid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='adminid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loginuser'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loginuser'),
        ),
    ]
