# Generated by Django 4.1.1 on 2022-11-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_loginuser"),
        ("main_page", "0009_remove_images__data_remove_images_createdat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compose",
            name="adminid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="adminid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
    ]
