# Generated by Django 4.1 on 2022-11-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_remove_images__data_remove_images_createdat_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='images',
        #     name='_data',
        # ),
        # migrations.RemoveField(
        #     model_name='images',
        #     name='createdAt',
        # ),
        # migrations.RemoveField(
        #     model_name='images',
        #     name='imagescol',
        # ),
        # migrations.RemoveField(
        #     model_name='images',
        #     name='updatedAt',
        # ),
    ]
