# Generated by Django 4.1.1 on 2022-11-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0010_alter_compose_adminid_alter_images_adminid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="resultImg/image%Y%m%d-%H%M%S"
            ),
        ),
    ]
