# Generated by Django 4.1.1 on 2022-11-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0011_images_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="images", name="photo",),
    ]
